### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by m44rtn** [m44rtn/vireo-kernel#9]
- [x] fix issues in the refman

**Comment by m44rtn** [comment]
- [ ] refman screen_basic function listing

**Comment by m44rtn** [comment]
- [ ] everything docced?

**Comment by m44rtn** [comment]
- [ ] comments that need to be removed?

**Comment by m44rtn** [comment]
- [ ] result == 0, util

**Comment by m44rtn** [comment]
- [ ] an assert? http://www.cplusplus.com/reference/cassert/assert/

**Comment by m44rtn** [comment]
- [ ] update readme

**Comment by m44rtn** [comment]
- [  ] documentation

**Comment by m44rtn** [comment]
This has moved to Trello
